version: '3.9'

services:
  sobok-graphql-server:
    build: .
    container_name: sobok-graphql-server
    env_file: .env
    image: sobok-graphql-server:latest
    # restart: always
    ports:
      - $PORT:$PORT
#     volumes:
#       - 'sobok:/server'
# volumes:
#   sobok:
