#!/bin/sh
ENV_FILE_PATH=${1-.env.development}

if [ ! -f $ENV_FILE_PATH ]; then
  echo "$ENV_FILE_PATH 파일이 존재하지 않습니다. $ENV_FILE_PATH 파일을 생성한 후 다시 시도해주세요."
  exit 1
fi

export $(grep -v '^#' $ENV_FILE_PATH | xargs)

echo $CONNECTION_STRING

rm -r database/data
mkdir database/data

psql $CONNECTION_STRING -Atc "SELECT schema_name FROM information_schema.schemata" |
  while read SCHEMA; do
    if [[ "$SCHEMA" != "pg_catalog" && "$SCHEMA" != "information_schema" ]]; then
      psql $CONNECTION_STRING -Atc "SELECT tablename FROM pg_tables WHERE schemaname='$SCHEMA'" |
        while read TBL; do
          psql $CONNECTION_STRING -c "COPY $SCHEMA.$TBL TO STDOUT WITH CSV DELIMITER ',' HEADER ENCODING 'UTF-8'" >database/data/$SCHEMA.$TBL.csv
        done
    fi
  done
