#!/bin/sh
export $(grep -v '^#' ${1-.env.development} | xargs)

CONNECTION_STRING="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
echo $CONNECTION_STRING

psql $CONNECTION_STRING -f database/initialization.sql

public_tables=(
  user
  leader_user_x_follower_user
  hashtag
  store
  store_x_hashtag
  menu
  menu_x_hashtag
  news
  news_x_tagged_menu
  trend
  feed
  feed_x_hashtag
  feed_x_rated_menu
  comment
  bucket
  bucket_x_menu
  bucket_x_store
  user_x_liked_comment
  user_x_liked_feed
  user_x_liked_menu
  user_x_liked_news
  user_x_liked_store
  user_x_liked_trend
)

deleted_tables=(
  user
  hashtag
  store
  menu
  news
  feed
  comment
  bucket
)

for public_table in "${public_tables[@]}"; do
  psql $CONNECTION_STRING -c "COPY public.${public_table} FROM STDIN WITH CSV DELIMITER ',' HEADER ENCODING 'UTF-8'" <database/schema/public.${public_table}.csv
done

for deleted_table in "${deleted_tables[@]}"; do
  psql $CONNECTION_STRING -c "COPY deleted.${deleted_table} FROM STDIN WITH CSV DELIMITER ',' HEADER ENCODING 'UTF-8'" <database/schema/deleted.${deleted_table}.csv
done
