name: Publish schema to Apollo Studio

version: 2

on:
  push:
    branches: [main]

jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      - run: npm install

      - run:
          name: Install Rover
          command: |
            # download and install Rover
            curl -sSL https://rover.apollo.dev/nix/v0.3.0 | sh

            # This allows the PATH changes to persist to the next `run` step
            echo 'export PATH=$HOME/.rover/bin:$PATH' >> $BASH_ENV

      # Start the GraphQL server.  If a different command is used to
      # start the server, use it in place of `npm start` here.
      - run:
          name: Starting server
          command: npm start
          background: true

      # make sure the server has enough time to start up before running
      # commands against it
      - run: sleep 5

      # When running on the 'main' branch, push the latest version
      # of the schema to Apollo Studio.
      - run: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
            rover graph publish my-graph@my-variant --schema ./schema.graphql
          fi

# # Controls when the action will run. Triggers the workflow on push or pull request events
# on:
#   push:
#     branches: [main]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "publish"
#   publish:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # https://docs.github.com/en/actions/reference/environments
#     environment: apollo

#     # https://docs.github.com/en/actions/reference/encrypted-secrets
#     # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
#     env:
#       APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
#       APOLLO_GRAPH_ID: ${{ secrets.APOLLO_GRAPH_ID }}
#       APOLLO_GRAPH_VARIANT: ${{ secrets.APOLLO_GRAPH_VARIANT }}
#       APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
#       GRAPHQL_SCHEMA: src/graphql/generated/schema.graphql

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Install Rover
#         run: |
#           curl -sSL https://rover.apollo.dev/nix/v0.2.0 | sh

#           # Add Rover to the $GITHUB_PATH so it can be used in another step
#           # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
#           echo "$HOME/.rover/bin" >> $GITHUB_PATH
#       - name: Publish schema against Sobok@current
#         run: |
#           rover graph publish ${{ env.APOLLO_GRAPH_ID }}@${{ env.APOLLO_GRAPH_VARIANT }} --schema ${{ env.GRAPHQL_SCHEMA }}
