name: Publish schema to Apollo Studio

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY_DEV }}
      APOLLO_GRAPH_ID: ${{ secrets.APOLLO_GRAPH_ID_DEV }}
      APOLLO_GRAPH_VARIANT: ${{ secrets.APOLLO_GRAPH_VARIANT_DEV }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
      GRAPHQL_SCHEMA: src/graphql/generated/schema.graphql

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.2.0 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish schema against Sobok-Dev@current
        run: |
          rover graph publish ${{ env.APOLLO_GRAPH_ID }}@${{ env.APOLLO_GRAPH_VARIANT }} --schema ${{ env.GRAPHQL_SCHEMA }}
